name: Deploy Functions

on:
  push:
    branches:
      - main

jobs:
  deploy_functions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Update to the latest version that supports Node.js 20

      - name: Set Up Node.js
        uses: actions/setup-node@v3  # Update to the latest version that supports Node.js 20
        with:
          node-version: '20'

      - name: Deploy Functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only functions --token $FIREBASE_TOKEN

